<Project Sdk="Microsoft.NET.Sdk">
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EFCore.NamingConventions" Version="10.0.0-rc.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\EventsResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>EventsResources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\EventsResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>EventsResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
</Project>
